
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.Button btn1;
	
	private global::Gtk.Button btn7;
	
	private global::Gtk.Button btn8;
	
	private global::Gtk.Button btn9;
	
	private global::Gtk.Button btn3;
	
	private global::Gtk.Button btn2;
	
	private global::Gtk.Button btn4;
	
	private global::Gtk.Button btn5;
	
	private global::Gtk.Button btn6;
	
	private global::Gtk.Button btn_subtracao;
	
	private global::Gtk.Button tbn_multiplicacao;
	
	private global::Gtk.Button btn_igual;
	
	private global::Gtk.Button btn_virgula;
	
	private global::Gtk.Button btn;
	
	private global::Gtk.Button btn_divisao;
	
	private global::Gtk.Button btn_adicao;
	
	private global::Gtk.Button btn_limpar;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.Entry txt_valor;
	
	private global::Gtk.Label label2;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Calculadora");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn1 = new global::Gtk.Button ();
		this.btn1.WidthRequest = 40;
		this.btn1.HeightRequest = 30;
		this.btn1.CanFocus = true;
		this.btn1.Name = "btn1";
		this.btn1.Label = global::Mono.Unix.Catalog.GetString ("1");
		this.fixed1.Add (this.btn1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btn1]));
		w1.X = 55;
		w1.Y = 63;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn7 = new global::Gtk.Button ();
		this.btn7.WidthRequest = 40;
		this.btn7.HeightRequest = 30;
		this.btn7.CanFocus = true;
		this.btn7.Name = "btn7";
		this.btn7.UseUnderline = true;
		this.btn7.Label = global::Mono.Unix.Catalog.GetString ("7");
		this.fixed1.Add (this.btn7);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btn7]));
		w2.X = 54;
		w2.Y = 137;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn8 = new global::Gtk.Button ();
		this.btn8.WidthRequest = 40;
		this.btn8.HeightRequest = 30;
		this.btn8.CanFocus = true;
		this.btn8.Name = "btn8";
		this.btn8.UseUnderline = true;
		this.btn8.Label = global::Mono.Unix.Catalog.GetString ("8");
		this.fixed1.Add (this.btn8);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btn8]));
		w3.X = 100;
		w3.Y = 137;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn9 = new global::Gtk.Button ();
		this.btn9.WidthRequest = 40;
		this.btn9.HeightRequest = 30;
		this.btn9.CanFocus = true;
		this.btn9.Name = "btn9";
		this.btn9.UseUnderline = true;
		this.btn9.Label = global::Mono.Unix.Catalog.GetString ("9");
		this.fixed1.Add (this.btn9);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btn9]));
		w4.X = 146;
		w4.Y = 137;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn3 = new global::Gtk.Button ();
		this.btn3.WidthRequest = 40;
		this.btn3.HeightRequest = 30;
		this.btn3.CanFocus = true;
		this.btn3.Name = "btn3";
		this.btn3.UseUnderline = true;
		this.btn3.Label = global::Mono.Unix.Catalog.GetString ("3");
		this.fixed1.Add (this.btn3);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btn3]));
		w5.X = 148;
		w5.Y = 64;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn2 = new global::Gtk.Button ();
		this.btn2.WidthRequest = 40;
		this.btn2.HeightRequest = 30;
		this.btn2.CanFocus = true;
		this.btn2.Name = "btn2";
		this.btn2.UseUnderline = true;
		this.btn2.Label = global::Mono.Unix.Catalog.GetString ("2");
		this.fixed1.Add (this.btn2);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btn2]));
		w6.X = 100;
		w6.Y = 63;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn4 = new global::Gtk.Button ();
		this.btn4.WidthRequest = 40;
		this.btn4.HeightRequest = 30;
		this.btn4.CanFocus = true;
		this.btn4.Name = "btn4";
		this.btn4.UseUnderline = true;
		this.btn4.Label = global::Mono.Unix.Catalog.GetString ("4");
		this.fixed1.Add (this.btn4);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btn4]));
		w7.X = 54;
		w7.Y = 100;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn5 = new global::Gtk.Button ();
		this.btn5.WidthRequest = 40;
		this.btn5.HeightRequest = 30;
		this.btn5.CanFocus = true;
		this.btn5.Name = "btn5";
		this.btn5.UseUnderline = true;
		this.btn5.Label = global::Mono.Unix.Catalog.GetString ("5");
		this.fixed1.Add (this.btn5);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btn5]));
		w8.X = 100;
		w8.Y = 100;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn6 = new global::Gtk.Button ();
		this.btn6.WidthRequest = 40;
		this.btn6.HeightRequest = 30;
		this.btn6.CanFocus = true;
		this.btn6.Name = "btn6";
		this.btn6.UseUnderline = true;
		this.btn6.Label = global::Mono.Unix.Catalog.GetString ("6");
		this.fixed1.Add (this.btn6);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btn6]));
		w9.X = 147;
		w9.Y = 98;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn_subtracao = new global::Gtk.Button ();
		this.btn_subtracao.WidthRequest = 40;
		this.btn_subtracao.HeightRequest = 30;
		this.btn_subtracao.CanFocus = true;
		this.btn_subtracao.Name = "btn_subtracao";
		this.btn_subtracao.UseUnderline = true;
		this.btn_subtracao.Label = global::Mono.Unix.Catalog.GetString ("-");
		this.fixed1.Add (this.btn_subtracao);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btn_subtracao]));
		w10.X = 191;
		w10.Y = 99;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.tbn_multiplicacao = new global::Gtk.Button ();
		this.tbn_multiplicacao.WidthRequest = 40;
		this.tbn_multiplicacao.HeightRequest = 30;
		this.tbn_multiplicacao.CanFocus = true;
		this.tbn_multiplicacao.Name = "tbn_multiplicacao";
		this.tbn_multiplicacao.UseUnderline = true;
		this.tbn_multiplicacao.Label = global::Mono.Unix.Catalog.GetString ("*");
		this.fixed1.Add (this.tbn_multiplicacao);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.tbn_multiplicacao]));
		w11.X = 191;
		w11.Y = 137;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn_igual = new global::Gtk.Button ();
		this.btn_igual.WidthRequest = 87;
		this.btn_igual.HeightRequest = 30;
		this.btn_igual.CanFocus = true;
		this.btn_igual.Name = "btn_igual";
		this.btn_igual.UseUnderline = true;
		this.btn_igual.Label = global::Mono.Unix.Catalog.GetString ("=");
		this.fixed1.Add (this.btn_igual);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btn_igual]));
		w12.X = 191;
		w12.Y = 171;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn_virgula = new global::Gtk.Button ();
		this.btn_virgula.WidthRequest = 40;
		this.btn_virgula.HeightRequest = 30;
		this.btn_virgula.CanFocus = true;
		this.btn_virgula.Name = "btn_virgula";
		this.btn_virgula.UseUnderline = true;
		this.btn_virgula.Label = global::Mono.Unix.Catalog.GetString (",");
		this.fixed1.Add (this.btn_virgula);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btn_virgula]));
		w13.X = 147;
		w13.Y = 170;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn = new global::Gtk.Button ();
		this.btn.WidthRequest = 87;
		this.btn.HeightRequest = 30;
		this.btn.CanFocus = true;
		this.btn.Name = "btn";
		this.btn.UseUnderline = true;
		this.btn.Label = global::Mono.Unix.Catalog.GetString ("0");
		this.fixed1.Add (this.btn);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btn]));
		w14.X = 53;
		w14.Y = 170;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn_divisao = new global::Gtk.Button ();
		this.btn_divisao.WidthRequest = 40;
		this.btn_divisao.HeightRequest = 30;
		this.btn_divisao.CanFocus = true;
		this.btn_divisao.Name = "btn_divisao";
		this.btn_divisao.UseUnderline = true;
		this.btn_divisao.Label = global::Mono.Unix.Catalog.GetString ("/");
		this.fixed1.Add (this.btn_divisao);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btn_divisao]));
		w15.X = 238;
		w15.Y = 137;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn_adicao = new global::Gtk.Button ();
		this.btn_adicao.WidthRequest = 40;
		this.btn_adicao.HeightRequest = 30;
		this.btn_adicao.CanFocus = true;
		this.btn_adicao.Name = "btn_adicao";
		this.btn_adicao.UseUnderline = true;
		this.btn_adicao.Label = global::Mono.Unix.Catalog.GetString ("+");
		this.fixed1.Add (this.btn_adicao);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btn_adicao]));
		w16.X = 239;
		w16.Y = 99;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn_limpar = new global::Gtk.Button ();
		this.btn_limpar.WidthRequest = 87;
		this.btn_limpar.HeightRequest = 30;
		this.btn_limpar.CanFocus = true;
		this.btn_limpar.Name = "btn_limpar";
		this.btn_limpar.UseUnderline = true;
		this.btn_limpar.Label = global::Mono.Unix.Catalog.GetString ("C");
		this.fixed1.Add (this.btn_limpar);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btn_limpar]));
		w17.X = 192;
		w17.Y = 64;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("MarcoScofield ®");
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w18.X = 116;
		w18.Y = 236;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txt_valor = new global::Gtk.Entry ();
		this.txt_valor.WidthRequest = 223;
		this.txt_valor.HeightRequest = 30;
		this.txt_valor.CanFocus = true;
		this.txt_valor.Name = "txt_valor";
		this.txt_valor.IsEditable = true;
		this.txt_valor.MaxLength = 20;
		this.txt_valor.InvisibleChar = '●';
		this.fixed1.Add (this.txt_valor);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txt_valor]));
		w19.X = 55;
		w19.Y = 29;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.fixed1.Add (this.label2);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
		w20.X = 57;
		w20.Y = 8;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 337;
		this.DefaultHeight = 270;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btn1.Clicked += new global::System.EventHandler (this.btnNumerador_Click);
		this.btn7.Clicked += new global::System.EventHandler (this.btnNumerador_Click);
		this.btn8.Clicked += new global::System.EventHandler (this.btnNumerador_Click);
		this.btn9.Clicked += new global::System.EventHandler (this.btnNumerador_Click);
		this.btn3.Clicked += new global::System.EventHandler (this.btnNumerador_Click);
		this.btn2.Clicked += new global::System.EventHandler (this.btnNumerador_Click);
		this.btn4.Clicked += new global::System.EventHandler (this.btnNumerador_Click);
		this.btn5.Clicked += new global::System.EventHandler (this.btnNumerador_Click);
		this.btn6.Clicked += new global::System.EventHandler (this.btnNumerador_Click);
		this.btn_subtracao.Clicked += new global::System.EventHandler (this.OnBtnSubtracaoClicked);
		this.tbn_multiplicacao.Clicked += new global::System.EventHandler (this.OnTbnMultiplicacaoClicked);
		this.btn_igual.Clicked += new global::System.EventHandler (this.OnBtnIgualClicked);
		this.btn_virgula.Clicked += new global::System.EventHandler (this.btnNumerador_Click);
		this.btn.Clicked += new global::System.EventHandler (this.btnNumerador_Click);
		this.btn_divisao.Clicked += new global::System.EventHandler (this.OnBtnDivisaoClicked);
		this.btn_adicao.Clicked += new global::System.EventHandler (this.OnBtnAdicaoClicked);
		this.btn_limpar.Clicked += new global::System.EventHandler (this.OnBtnLimparClicked);
	}
}
